server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.200.128
  rabbitmq:
    host: 192.168.200.128
    virtual-host: /haoge
    username: haoge
    password: haoge
gmall:
  jwt:
    pubKeyPath: C:\\project-0722\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
    userKey: user-key